### ISSUE TITLE
Conda and pip installs fail on fresh Anaconda (error having to do with "clock")

### ISSUE THREAD

**Issue by llorracc** [econ-ark/HARK#898]
On a fresh install of Anaconda 3, "conda install econ-ark" does not install a functioning version of HARK

**Transcript**
```
sudo conda install econ-ark
Password:
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.9.1
  latest version: 4.9.2

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /Volumes/Sync/Sys/OSX/linked/root/usr/local/bin/anaconda

  added / updated specs:
    - econ-ark


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2020.12.5  |       h033912b_0         138 KB  conda-forge
    certifi-2020.12.5          |   py38h50d1736_0         143 KB  conda-forge
    conda-4.9.2                |   py38h50d1736_0         3.1 MB  conda-forge
    dill-0.3.3                 |     pyhd8ed1ab_0          60 KB  conda-forge
    econ-ark-0.10.2            |             py_0         354 KB  conda-forge
    openssl-1.1.1i             |       h35c211d_0         1.9 MB  conda-forge
    ------------------------------------------------------------
                                           Total:         5.6 MB

The following NEW packages will be INSTALLED:

  dill               conda-forge/noarch::dill-0.3.3-pyhd8ed1ab_0
  econ-ark           conda-forge/noarch::econ-ark-0.10.2-py_0

The following packages will be UPDATED:

  ca-certificates                      2020.6.20-hecda079_0 --> 2020.12.5-h033912b_0
  certifi                          2020.6.20-py38h5347e94_2 --> 2020.12.5-py38h50d1736_0
  conda               pkgs/main::conda-4.9.1-py38hecd8cb5_0 --> conda-forge::conda-4.9.2-py38h50d1736_0
  openssl                                 1.1.1h-haf1e3a3_0 --> 1.1.1i-h35c211d_0



Downloading and Extracting Packages
openssl-1.1.1i       | 1.9 MB    | ########################################################################################################################## | 100% 
conda-4.9.2          | 3.1 MB    | ########################################################################################################################## | 100% 
dill-0.3.3           | 60 KB     | ########################################################################################################################## | 100% 
ca-certificates-2020 | 138 KB    | ########################################################################################################################## | 100% 
econ-ark-0.10.2      | 354 KB    | ########################################################################################################################## | 100% 
certifi-2020.12.5    | 143 KB    | ########################################################################################################################## | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(base) JHUEconCDC@JHUEconCDC:~ $ python
Python 3.8.3 (default, Jul  2 2020, 11:26:31) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import HARK
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Volumes/Sync/Sys/OSX/linked/root/usr/local/bin/anaconda/lib/python3.8/site-packages/HARK/__init__.py", line 2, in <module>
    from .core import *
  File "/Volumes/Sync/Sys/OSX/linked/root/usr/local/bin/anaconda/lib/python3.8/site-packages/HARK/core.py", line 21, in <module>
    from time import clock
ImportError: cannot import name 'clock' from 'time' (unknown location)
```

**Desktop (please complete the following information):**
MacOS 10.15.2
Econ-ARK version: Default as of 2020-12-28
Python 3.8.3

**Comment by MridulS** [comment]
Does putting `-c conda-forge` explicitly in the installation work?
```
conda install -c conda-forge econ-ark 
```

**Comment by MridulS** [comment]
ah no, this was because econ-ark wasn't being built for python3.8 and conda.

This should be fixed now, made a new build on conda which works with python3.8.

**Comment by MridulS** [comment]
the new build on conda solve this.
